name: geo-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - backports.zstd=1.3.0=py313h18e8e13_0
  - blosc=1.21.6=he440d0b_1
  - branca=0.8.2=pyhd8ed1ab_0
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - brotli-python=1.2.0=py313hf159716_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - contourpy=1.3.3=py313hc8edb43_4
  - cycler=0.12.1=pyhcf101f3_2
  - folium=0.20.0=pyhd8ed1ab_0
  - fonttools=4.61.1=py313h3dea7bd_0
  - freetype=2.14.1=ha770c72_0
  - freexl=2.0.0=h9dce30a_2
  - geopandas=1.1.2=pyhd8ed1ab_0
  - geopandas-base=1.1.2=pyha770c72_0
  - geos=3.14.1=h480dda7_0
  - giflib=5.2.2=hd590300_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h33c6efd_0
  - idna=3.11=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - json-c=0.18=h6688a6e_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py313hc8edb43_2
  - krb5=1.21.3=h659f571_0
  - lcms2=2.18=h0c24ade_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - lerc=4.0.0=h0aef613_1
  - libarchive=3.8.5=gpl_hc2c16d8_100
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcblas=3.11.0=5_h0358290_openblas
  - libcurl=8.18.0=h4e3cde8_0
  - libdeflate=1.25=h17f619e_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h3435931_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgdal-core=3.12.1=hf05ffb4_1
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=he0feb66_16
  - libhwy=1.3.0=h4c17acf_1
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - libjxl=0.11.1=ha09017c_8
  - libkml=1.3.0=haa4a5bd_1022
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblzma=5.8.2=hb03c661_0
  - libmpdec=4.0.0=hb03c661_1
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libpng=1.6.54=h421ea60_0
  - librttopo=1.1.0=h46dd2a8_20
  - libspatialite=5.1.0=gpl_h2abfd87_119
  - libsqlite=3.51.2=hf4e2dac_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libtiff=4.7.1=h9d88235_1
  - libuuid=2.41.3=h5347b49_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libxml2-devel=2.15.1=he237659_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=h280c20c_1002
  - mapclassify=2.10.0=pyhd8ed1ab_1
  - markupsafe=3.0.3=py313h3dea7bd_0
  - matplotlib-base=3.10.8=py313h683a580_0
  - minizip=4.0.10=h05a5f5f_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - muparser=2.3.5=h5888daf_0
  - ncurses=6.5=h2d0b736_3
  - networkx=3.6.1=pyhcf101f3_0
  - numpy=2.4.2=py313hf6604e3_0
  - openjpeg=2.5.4=h55fea9a_0
  - openssl=3.6.1=h35e630c_1
  - packaging=26.0=pyhcf101f3_0
  - pandas=3.0.0=py313hbfd7664_0
  - pcre2=10.47=haa7fec5_0
  - pillow=12.1.0=py313h80991f8_0
  - pip=26.0=pyh145f28c_0
  - proj=9.7.1=he0df7b0_2
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyogrio=0.12.1=py313hae45665_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pyproj=3.7.2=py313h77f6078_2
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.13.11=hc97d973_101_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.13=8_cp313
  - qhull=2020.2=h434a139_5
  - readline=8.3=h853b02a_0
  - requests=2.32.5=pyhcf101f3_1
  - scikit-learn=1.8.0=np2py313h16d504d_1
  - scipy=1.17.0=py313h4b8bb8b_1
  - setuptools=80.10.2=pyh332efcf_0
  - shapely=2.1.2=py313had47c43_2
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_1
  - sqlite=3.51.2=h04a0ce9_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_h366c992_103
  - tzdata=2025c=hc9c84f9_1
  - uriparser=0.9.8=hac33072_0
  - urllib3=2.6.3=pyhd8ed1ab_0
  - xerces-c=3.3.0=hd9031aa_1
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.3.2=hceb46e0_1
  - zstd=1.5.7=hb78ec9c_6
prefix: /home/mina/miniconda3/envs/geo-env
